In [ ]:
NUMPY

NumPy:Numerical python it is a kind of librabry which works with array.
Array:It is a collection of homogenous element(same data type).
- stored in contiguous memory.
- we can use NumPy while working with large datatypes,numbers,cal,matrics,statistics(sum,avg,mul,matrix oper)
- import numpy as np
- even if we use list y numpy means:Fast,consume less memory,easy for cal
- vector: it is simply a list/array of numbers arranged in one direction.

In [18]:
import numpy as np
arr=np.array([1,2,3,4,5])#row vector
print(arr)

[1 2 3 4 5]

In [6]:
#addn operation
a=np.array([1,3,4,5,2,5,6])
print(a+3)
print(a*3)
print(a++3)
print(a-3)

[4 6 7 8 5 8 9]
[ 3  9 12 15  6 15 18]
[4 6 7 8 5 8 9]
[-2  0  1  2 -1  2  3]

In [9]:
#n.dim: it will give the dimension of array.
a.ndim

1

In [10]:
#n.shape:It is a tuple which returns the no.of elements per axis
a.shape

(7,)

In [13]:
#n.dtype: It returns data type
a.dtype

dtype('int64')

In [14]:
#n.size: It counts the no.of elements
a.size

7

In [25]:
a=np.array([[1],[3],[4],[5],[2],[5],[6]])
print(a)
#index start with 0

[[1]
 [3]
 [4]
 [5]
 [2]
 [5]
 [6]]

In [26]:
a.shape

(7, 1)

In [29]:
data=np.array([[1,2,3],[3,55,67],[00,00,000]])
print(data)

[[ 1  2  3]
 [ 3 55 67]
 [ 0  0  0]]

In [31]:
data.size

9

In [32]:
data.shape#no.of rows and columns

(3, 3)

In [36]:
d1=data[:,0:2]#from data 2 columns
d1

array([[ 1,  2],
       [ 3, 55],
       [ 0,  0]])

In [39]:
#statistical operation
d2=data[:,0:1]
d2

array([[1],
       [3],
       [0]])

- mean:addn of all values/no.of values
- meadian:exact middle point after sorting(0,1,3)
- mode:Frequent occurance of any value
- standard deviation:deviation from mean
- var:spread of data

In [40]:
print ("Mean:",np.mean(d1))
print ("Median:",np.median(d1))
#np has no attribute mode

Mean: 10.166666666666666
Median: 1.5

In [42]:
print ("Min:",np.mean(d2))
print ("Max:",np.mean(d2))

Min: 1.3333333333333333
Max: 1.3333333333333333

In [43]:
print ("Standard deviation:",np.mean(d1))
print ("Variance:",np.mean(d1))

Standard deviation: 10.166666666666666
Variance: 10.166666666666666

NUMPY ARITHEMATIC

In [44]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [46]:
b=np.array([[10,20,30],[1,2,3],[4,4,4]])
print(b)

[[10 20 30]
 [ 1  2  3]
 [ 4  4  4]]

In [47]:
a+b

array([[11, 22, 33],
       [ 5,  7,  9],
       [11, 12, 13]])

In [48]:
a/b

array([[0.1 , 0.1 , 0.1 ],
       [4.  , 2.5 , 2.  ],
       [1.75, 2.  , 2.25]])

In [49]:
a//b

array([[0, 0, 0],
       [4, 2, 2],
       [1, 2, 2]])

In [50]:
a%b

array([[1, 2, 3],
       [0, 1, 0],
       [3, 0, 1]])

In [51]:
np.random.random(10)#it will print 10 values between 0 and 1

array([0.36563776, 0.86751402, 0.81582548, 0.22325448, 0.05622271,
       0.15339772, 0.60529661, 0.51994413, 0.75003441, 0.21858605])

In [54]:
a1=np.random.randint(10, size=7)#print between 0 to 9
a1

array([8, 4, 9, 8, 8, 6, 8], dtype=int32)

In [56]:
a2=np.random.randint(10, size=(3,2,3))#print between 0 to 9
a2

array([[[5, 2, 9],
        [8, 6, 2]],

       [[0, 2, 2],
        [3, 6, 6]],

       [[4, 9, 0],
        [9, 6, 2]]], dtype=int32)

In [57]:
a2.ndim

3

In [58]:
data

array([[ 1,  2,  3],
       [ 3, 55, 67],
       [ 0,  0,  0]])

In [59]:
import pandas as pd
data=pd.DataFrame(data)
data

   0   1   2
0  1   2   3
1  3  55  67
2  0   0   0

In [60]:
data.columns=["Age","hgt","wgt"]
data

   Age  hgt  wgt
0    1    2    3
1    3   55   67
2    0    0    0